definitions:
  auth.SignInReqBody:
    properties:
      email:
        type: string
      password:
        maxLength: 32
        minLength: 12
        type: string
    required:
    - email
    - password
    type: object
  auth.SignInResp200Body:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  auth.SignUpReqBody:
    properties:
      email:
        type: string
      password:
        maxLength: 32
        minLength: 12
        type: string
    required:
    - email
    - password
    type: object
  healthz.HealthzRespBody:
    properties:
      env:
        type: string
      status:
        type: string
    required:
    - env
    - status
    type: object
info:
  contact: {}
  description: This is a sample server for GoDelivery Auth Service.
  title: GoDelivery Auth Service
  version: "1.0"
paths:
  /api/auth/signin:
    post:
      description: SignIn
      parameters:
      - description: SignIn request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.SignInReqBody'
      responses:
        "200":
          description: SingIn success
          schema:
            $ref: '#/definitions/auth.SignInResp200Body'
        "401":
          description: invalid credentials
          schema:
            type: string
      summary: SignIn
      tags:
      - Auth
  /api/auth/signup:
    post:
      description: SingUp
      parameters:
      - description: SingUp request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.SignUpReqBody'
      responses:
        "200":
          description: SingUp success
          schema:
            type: string
        "409":
          description: user already exists
          schema:
            type: string
      summary: SingUp
      tags:
      - Auth
  /api/healthz:
    get:
      consumes:
      - application/json
      description: Healthz check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/healthz.HealthzRespBody'
        "500":
          description: internal server error
          schema:
            type: string
      summary: Healthz check
      tags:
      - Healthz
swagger: "2.0"
