services:
  postgres:
    image: postgres:17.4
    container_name: postgres_container
    restart: no
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_CONTAINER_PORT}
    #volumes:
    #  - ./services/auth/db/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $AUTH_POSTGRES_USER -d $AUTH_POSTGRES_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    tty: true
    stdin_open: true

  redis:
    image: redis:7.2
    container_name: redis_container
    restart: no
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./scripts/entrypoint.sh:/usr/local/bin/entrypoint.sh
    entrypoint: [ "sh", "/usr/local/bin/entrypoint.sh" ]
    healthcheck:
      test: [ "CMD", "redisClient-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    tty: true
    stdin_open: true

  auth_service:
    build:
      context: .
      target: dev
      dockerfile: ./services/auth/Dockerfile
    env_file:
      - .env
    container_name: auth_service
    volumes:
      - ./services/auth/cmd:/auth_service/cmd
      - ./services/auth/internal:/auth_service/internal
      - ./services/auth/migrations:/auth_service/migrations
    ports:
      - "8081:8081"