services:
  auth_service:
    build:
      context: .
      target: dev
      dockerfile: ./services/auth/Dockerfile
    container_name: auth_service

    volumes:
      - ./services/auth/cmd:/work/cmd
      - ./services/auth/internal:/work/internal
    ports:
      - "8081:8081"
    env_file: ./services/auth/.env